apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: postgres-operator
  name: astra-pg-backup
spec:
  schedule: "0/1 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: pgo-admin-sa
          volumes:
            - name: astra-control-config
              secret:
                secretName: astra-control-config
          containers:
          - name: alpine-actoolkit
            image: alpine:latest
            imagePullPolicy: IfNotPresent
            env:
              - name: BACKUPS_TO_KEEP
                value: "3"
              - name: APP_ID
                value: "c606d0f7-3b9f-425a-ac9a-edde98b07f61"
              - name: PGDB_NAME
                value: "pg-crunchy-test"
              - name: PGBACKREST_REPO
                value: "repo1"
              - name: KUBECTL_VERSION
                value: "1.23.9"
              - name: KUBECTL_PGO_VERSION
                value: "0.2.0"
              - name: ACTOOLKIT_VERSION
                value: "2.6.0"
              - name: PGBACKREST_TIMEOUT
                value: "30"
              - name: ASTRA_BACKUP_POLL_INTERVAL
                value: "60"
            command: ["/bin/sh"]
            args:
            - -c
            - >
              echo "Starting install" &&
              apk add py3-pip curl jq &&
              apk add gcompat &&
              python3 -m pip install --upgrade pip &&
              python3 -m pip install actoolkit==$ACTOOLKIT_VERSION &&
              curl -sLO https://storage.googleapis.com/kubernetes-release/release/v${KUBECTL_VERSION}/bin/linux/amd64/kubectl &&
              mv kubectl /usr/bin/kubectl &&
              chmod +x /usr/bin/kubectl && 
              echo "Starting file download and execution" &&
              curl -sLO https://raw.githubusercontent.com/MichaelHaigh/k8scron-astra-backup/main/backup.sh &&
              curl -sLO https://github.com/CrunchyData/postgres-operator-client/releases/download/v${KUBECTL_PGO_VERSION}/kubectl-pgo-linux-amd64 &&
              mv kubectl-pgo-linux-amd64 /usr/local/bin/kubectl-pgo &&
              chmod +x /usr/local/bin/kubectl-pgo &&
              sh backup.sh "postgres-operator" $PGDB_NAME $APP_ID $BACKUPS_TO_KEEP $PGBACKREST_REPO $PGBACKREST_TIMEOUT $ASTRA_BACKUP_POLL_INTERVAL
            volumeMounts:
              - mountPath: /etc/astra-toolkits
                name: astra-control-config
                readOnly: true
          restartPolicy: Never
