apiVersion: batch/v1
kind: CronJob
metadata:
  name: astra-pg-backup
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: astra-control-config
              secret:
                secretName: astra-control-config
          containers:
          - name: alpine-actoolkit
            image: alpine:latest
            imagePullPolicy: IfNotPresent
            env:
              - name: BACKUPS_TO_KEEP
                value: "3"
              - name: APP_ID
                value: "9c3be07e-96ae-4828-8dfe-3eec1c924d12"
	      - name: PGBACKREST_REPO
	        value: "pgtest_repo"
              - name: KUBECTL_VERSION
                value: "1.23.9"
              - name: ACTOOLKIT_VERSION
                value: "2.6.0"
            command: ["/bin/sh"]
            args:
            - -c
            - >
              echo "Starting install" &&
              apk add py3-pip curl jq &&
              python3 -m pip install --upgrade pip &&
              python3 -m pip install actoolkit==$ACTOOLKIT_VERSION &&
              curl -sLO https://storage.googleapis.com/kubernetes-release/release/v${KUBECTL_VERSION}/bin/linux/amd64/kubectl &&
              mv kubectl /usr/bin/kubectl &&
              chmod +x /usr/bin/kubectl && 
              echo "Starting file download and execution" &&
              curl -sLO https://raw.githubusercontent.com/MichaelHaigh/k8scron-astra-backup/main/backup.sh &&
	      curl -sLO https://raw.githubusercontent.com/MichaelHaigh/k8scron-astra-backup/main/kubectl-pgo &&
	      mv kubectl-pgo /usr/local/bin/kubectl-pgo &&
	      chmod +x /usr/local/bin/kubectl-pgo &&
              sh backup.sh $APP_ID $BACKUPS_TO_KEEP PGBACKREST_REPO
            volumeMounts:
              - mountPath: /etc/astra-toolkits
                name: astra-control-config
                readOnly: true
          restartPolicy: Never
