apiVersion: batch/v1
kind: CronJob
metadata:
  name: astra-pg-backup
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: astra-control-config
              secret:
                secretName: astra-control-config
          containers:
          - name: alpine-actoolkit
            image: alpine:latest
            imagePullPolicy: IfNotPresent
            env:
              - name: BACKUPS_TO_KEEP
                value: "10"
              - name: APP_ID
                value: "f09769fa-9841-44a5-9f81-f621748d9c7b"
              - name: KUBECTL_VERSION
                value: "1.23.9"
              - name: ACTOOLKIT_VERSION
                value: "2.6.0"
            command: ["/bin/sh"]
            args:
            - -c
            - >
              echo "Starting install" &&
              apk add py3-pip curl jq &&
              python3 -m pip install --upgrade pip &&
              python3 -m pip install actoolkit==$ACTOOLKIT_VERSION &&
              curl -sLO https://storage.googleapis.com/kubernetes-release/release/v${KUBECTL_VERSION}/bin/linux/amd64/kubectl &&
              mv kubectl /usr/bin/kubectl &&
              chmod +x /usr/bin/kubectl && 
              echo "Starting file download and execution" &&
              curl -sLO https://raw.githubusercontent.com/MichaelHaigh/k8scron-astra-backup/main/backup.sh &&
              sh backup.sh $APP_ID $BACKUPS_TO_KEEP
            volumeMounts:
              - mountPath: /etc/astra-toolkits
                name: astra-control-config
                readOnly: true
          restartPolicy: Never
